# Generated by Django 5.1.6 on 2025-02-07 19:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admin_panel", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="status",
            field=models.BooleanField(default=True),
        ),
    ]
