# Generated by Django 5.1.6 on 2025-02-28 21:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admin_panel", "0002_user_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="signature_image",
            field=models.ImageField(blank=True, null=True, upload_to="signatures/"),
        ),
    ]
