# Generated by Django 5.1.6 on 2025-03-03 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admin_panel", "0005_texasresidencyaffidavit"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ferpaform",
            name="review_comments",
        ),
        migrations.RemoveField(
            model_name="ferpaform",
            name="reviewed_at",
        ),
        migrations.RemoveField(
            model_name="ferpaform",
            name="reviewer",
        ),
        migrations.RemoveField(
            model_name="ferpaform",
            name="status",
        ),
        migrations.RemoveField(
            model_name="ferpaform",
            name="submitted_at",
        ),
        migrations.RemoveField(
            model_name="ferpaform",
            name="user",
        ),
        migrations.RemoveField(
            model_name="texasresidencyaffidavit",
            name="review_comments",
        ),
        migrations.RemoveField(
            model_name="texasresidencyaffidavit",
            name="reviewed_at",
        ),
        migrations.RemoveField(
            model_name="texasresidencyaffidavit",
            name="reviewer",
        ),
        migrations.RemoveField(
            model_name="texasresidencyaffidavit",
            name="status",
        ),
        migrations.RemoveField(
            model_name="texasresidencyaffidavit",
            name="submitted_at",
        ),
        migrations.RemoveField(
            model_name="texasresidencyaffidavit",
            name="user",
        ),
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("ferpa", "FERPA Authorization"),
                            ("texas_residency", "Texas Residency Affidavit"),
                            ("other", "Other Application Type"),
                        ],
                        max_length=50,
                    ),
                ),
                ("application_name", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending", "Pending Approval"),
                            ("approved", "Approved"),
                            ("returned", "Returned for Revision"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("review_comments", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "reviewer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_applications",
                        to="admin_panel.user",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="admin_panel.user",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="ferpaform",
            name="application",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ferpa_form",
                to="admin_panel.application",
            ),
        ),
        migrations.AddField(
            model_name="texasresidencyaffidavit",
            name="application",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="texas_residency_affidavit",
                to="admin_panel.application",
            ),
        ),
    ]
