# Generated by Django 5.1.6 on 2025-04-17 19:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admin_panel", "0006_remove_ferpaform_review_comments_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="cougar_id",
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name="ferpaform",
            name="form_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
