# Generated by Django 5.1.6 on 2025-04-20 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admin_panel", "0008_department_user_department"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="admin_panel.department",
            ),
        ),
    ]
