# Generated by Django 5.1.6 on 2025-04-20 23:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admin_panel", "0009_application_department"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApprovalRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "form_type",
                    models.CharField(
                        choices=[
                            ("ferpa", "FERPA Authorization"),
                            ("texas_residency", "Texas Residency Affidavit"),
                        ],
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "departments_required",
                    models.ManyToManyField(to="admin_panel.department"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DepartmentApproval",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("approved_at", models.DateTimeField(auto_now_add=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="admin_panel.application",
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="admin_panel.user",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="admin_panel.department",
                    ),
                ),
            ],
            options={
                "unique_together": {("application", "department")},
            },
        ),
    ]
